py_test(
    name = "px_tests",
    srcs = [
        'px_commandline_test.py',
        'px_cpuinfo_test.py',
        'px_file_test.py',
        'px_ipc_map_test.py',
        'px_load_bar_test.py',
        'px_load_test.py',
        'px_loginhistory_test.py',
        'px_process_test.py',
        'px_processinfo_test.py',
        'px_terminal_test.py',
        'px_top_test.py',
        'testutils.py',
    ],

    deps = [
        "//px",
    ],
)
