.Dd August 26, 2018
.Dt PTOP 1
.Os
.Sh NAME
.Nm ptop
.Nd display and update sorted information about processes
.Sh SYNOPSIS
.\" FIXME: Other man pages don't need to use \p to break lines here,
.\" and use the Nm macro for the command name. Why can't we?
.Ic Nm
.Sh DESCRIPTION
.Nm
periodically displays a sorted list of system processes.
Processes are sorted with the highest CPU users at the top.
To stabilize the list, CPU usage is measured from when
.Nm
was started.
.Sh PROCESS NAMING
.Nm
tries to be helpful about naming processes, and avoid printing names
of various VMs.
.Pp
For example, if you do
.Ql java -jar foo.jar
,
.Nm
will show this process as
.Ql foo.jar
rather than
.Ql java
\&.
.Nm
parses command lines from:
.Bl -bullet
.It
Java
.It
Python
.It
Node
.It
Ruby
.It
Various shells
.It
Perl
.El
.Sh SEE ALSO
.Xr px 1 ,
.Xr top 1
.Sh HOMEPAGE
.Nm
lives at http://github.com/walles/px
