name: macOS CI
on: [push, pull_request]
jobs:
  tox:
    runs-on: macos-10.15
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # For getting tags from the repo
      - name: Create a virtualenv
        run: |
          python3 -m venv env
      - name: Install tox in our virtualenv
        run: |
          . ./env/bin/activate
          pip install tox
      - name: Run tox in our virtualenv
        run: |
          . ./env/bin/activate

          # Explicitly name environments we think can detect macOS specific problems.
          # All (others) will be run on Linux.
          #
          # The point is to run as little as possible on macOS because macOS runs are
          # slow and expensive, look for "multiplier" on this page:
          # https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
          tox -e version.py,installtest,pytest3,package,test-package,test-wheel
